version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: example-postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: example-api
    depends_on:
      - postgres
    ports:
      - "3022:3022"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: testdb
    restart: always

volumes:
  pg_data:
